sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test 

# deploy:
#   provider:
#   region:
#   app: "docker-react"
#   env: "docker-react-env"
#   bucket_name: ""
#   bucket_path: ""
#   on:
#     branch: master
#   access_key_id:
#   secret_access_key:
#     secure:
